### ISSUE TITLE
Question: Required Image Dimension?

### ISSUE THREAD

**Issue by roserustowicz** [dlr-eoc/ukis-csmask#12]
Hi, I'm curious what image shapes the algorithm is expected to perform well on. Is there a range of image dimensions (rows, columns) of 30m pixels that the algorithm is limited to? 

For example, is it expected to perform on a 16x16 image, in the same way that it would perform on a 512x512 image? 

I see from the paper that the model was trained on 256x256 images, and assume the receptive field is likely constrained when image dimensions are too small, but the algorithm did not throw any errors when I used a very small image size (7x7 pixels).

Thank you!

**Comment by fwfichtner** [comment]
I am not sure if we tried that, @MWieland might be able to answer this question better. My general feeling is that you are right.

If @MWieland agrees we could warn the user when the image dimension is too far from 256x256, I would not throw an error.

**Comment by MWieland** [comment]
The model has been trained with 256x256 image tiles. I agree that it makes sense to issue a warning in case an input image of less than this dimension is provided. The results may still make sense but the user should be aware of this an critically revise
